# Generated by Django 5.1.1 on 2024-10-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EmployeeManagementSystem", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="user_gender",
            field=models.SmallIntegerField(
                choices=[(1, "male"), (2, "female")], verbose_name="gender"
            ),
        ),
    ]
