# Generated by Django 5.1.1 on 2024-10-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EmployeeManagementSystem", "0002_alter_userinfo_user_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="user_gender",
            field=models.SmallIntegerField(
                choices=[(2, "female"), (1, "male")], verbose_name="gender"
            ),
        ),
    ]
