# Generated by Django 5.1.1 on 2024-10-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "EmployeeManagementSystem",
            "0006_admin_alter_prettynum_level_alter_prettynum_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="prettynum",
            name="level",
            field=models.SmallIntegerField(
                choices=[(1, "VIP1"), (0, "Normal"), (3, "VIP3"), (2, "VIP2")],
                default=0,
                verbose_name="Level",
            ),
        ),
        migrations.AlterField(
            model_name="prettynum",
            name="status",
            field=models.SmallIntegerField(
                choices=[(0, "Normal"), (1, "Disabled")],
                default=0,
                verbose_name="Status",
            ),
        ),
    ]
