# Generated by Django 5.1.1 on 2024-10-02 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "EmployeeManagementSystem",
            "0007_alter_prettynum_level_alter_prettynum_status",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Boss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="姓名")),
                ("age", models.IntegerField(verbose_name="年龄")),
                ("img", models.CharField(max_length=128, verbose_name="头像")),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="名称")),
                ("count", models.IntegerField(verbose_name="人口")),
                (
                    "img",
                    models.FileField(
                        max_length=128, upload_to="city/", verbose_name="Logo"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="XX",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32, verbose_name="名称")),
                ("image", models.FileField(upload_to="avatar/", verbose_name="头像")),
            ],
        ),
        migrations.AlterField(
            model_name="prettynum",
            name="level",
            field=models.SmallIntegerField(
                choices=[(2, "VIP2"), (3, "VIP3"), (0, "Normal"), (1, "VIP1")],
                default=0,
                verbose_name="Level",
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="gender",
            field=models.SmallIntegerField(
                choices=[(1, "male"), (2, "female")], verbose_name="gender"
            ),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("oid", models.CharField(max_length=64, verbose_name="订单号")),
                ("title", models.CharField(max_length=32, verbose_name="名称")),
                ("price", models.IntegerField(verbose_name="价格")),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "待支付"), (2, "已支付")], default=1, verbose_name="状态"
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EmployeeManagementSystem.admin",
                        verbose_name="管理员",
                    ),
                ),
            ],
        ),
    ]
